import type { ElementCategory } from "@/types";

export type PeriodicElement = {
  symbol: string;
  name: string;
  atomicNumber: number;
  atomicMass: number;
  period: number;
  group: number;
  category: ElementCategory;
  categoryLabel: string;
  electronConfiguration: string;
  commonUses: string;
  explanation: string;
  gridRow: number;
  gridCol: number;
};

export const elementCategories: {
  id: ElementCategory;
  label: string;
  color: string;
}[] = [
  { id: "alkali-metal", label: "Alkali metals", color: "#f87171" },
  { id: "alkaline-earth", label: "Alkaline earth metals", color: "#fb923c" },
  { id: "transition-metal", label: "Transition metals", color: "#fbbf24" },
  { id: "post-transition-metal", label: "Post-transition metals", color: "#a3e635" },
  { id: "metalloid", label: "Metalloids", color: "#34d399" },
  { id: "reactive-nonmetal", label: "Nonmetals", color: "#22d3ee" },
  { id: "noble-gas", label: "Noble gases", color: "#a78bfa" },
  { id: "lanthanide", label: "Lanthanides", color: "#f472b6" },
  { id: "actinide", label: "Actinides", color: "#e879f9" },
];

export const periodicElements: PeriodicElement[] = [
  {
    "symbol": "H",
    "name": "Hydrogen",
    "atomicNumber": 1,
    "atomicMass": 1.008,
    "period": 1,
    "group": 1,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "1s1",
    "commonUses": "Fuel cells, ammonia production",
    "explanation": "Lightest element; one proton and one electron.",
    "gridRow": 1,
    "gridCol": 1
  },
  {
    "symbol": "He",
    "name": "Helium",
    "atomicNumber": 2,
    "atomicMass": 4.003,
    "period": 1,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "1s2",
    "commonUses": "Balloons, cryogenics, MRI cooling",
    "explanation": "Inert noble gas; second most abundant in universe.",
    "gridRow": 1,
    "gridCol": 18
  },
  {
    "symbol": "Li",
    "name": "Lithium",
    "atomicNumber": 3,
    "atomicMass": 6.94,
    "period": 2,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[He] 2s1",
    "commonUses": "Batteries, ceramics, mood stabilizers",
    "explanation": "Soft alkali metal; highly reactive with water.",
    "gridRow": 2,
    "gridCol": 1
  },
  {
    "symbol": "Be",
    "name": "Beryllium",
    "atomicNumber": 4,
    "atomicMass": 9.012,
    "period": 2,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[He] 2s2",
    "commonUses": "Aerospace alloys, X-ray windows",
    "explanation": "Lightweight alkaline earth metal; toxic dust.",
    "gridRow": 2,
    "gridCol": 2
  },
  {
    "symbol": "B",
    "name": "Boron",
    "atomicNumber": 5,
    "atomicMass": 10.81,
    "period": 2,
    "group": 13,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[He] 2s2 2p1",
    "commonUses": "Borosilicate glass, detergents, semiconductors",
    "explanation": "Metalloid essential for plant cell walls.",
    "gridRow": 2,
    "gridCol": 13
  },
  {
    "symbol": "C",
    "name": "Carbon",
    "atomicNumber": 6,
    "atomicMass": 12.011,
    "period": 2,
    "group": 14,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[He] 2s2 2p2",
    "commonUses": "Steel, plastics, fuels, life molecules",
    "explanation": "Basis of organic chemistry and life.",
    "gridRow": 2,
    "gridCol": 14
  },
  {
    "symbol": "N",
    "name": "Nitrogen",
    "atomicNumber": 7,
    "atomicMass": 14.007,
    "period": 2,
    "group": 15,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[He] 2s2 2p3",
    "commonUses": "Fertilizers, food preservation, explosives",
    "explanation": "Makes up 78% of Earth atmosphere.",
    "gridRow": 2,
    "gridCol": 15
  },
  {
    "symbol": "O",
    "name": "Oxygen",
    "atomicNumber": 8,
    "atomicMass": 15.999,
    "period": 2,
    "group": 16,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[He] 2s2 2p4",
    "commonUses": "Respiration, steelmaking, water treatment",
    "explanation": "Essential for combustion and aerobic life.",
    "gridRow": 2,
    "gridCol": 16
  },
  {
    "symbol": "F",
    "name": "Fluorine",
    "atomicNumber": 9,
    "atomicMass": 18.998,
    "period": 2,
    "group": 17,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[He] 2s2 2p5",
    "commonUses": "Toothpaste, Teflon, uranium enrichment",
    "explanation": "Most electronegative and reactive element.",
    "gridRow": 2,
    "gridCol": 17
  },
  {
    "symbol": "Ne",
    "name": "Neon",
    "atomicNumber": 10,
    "atomicMass": 20.18,
    "period": 2,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[He] 2s2 2p6",
    "commonUses": "Neon signs, high-voltage indicators",
    "explanation": "Noble gas that glows red-orange in discharge tubes.",
    "gridRow": 2,
    "gridCol": 18
  },
  {
    "symbol": "Na",
    "name": "Sodium",
    "atomicNumber": 11,
    "atomicMass": 22.99,
    "period": 3,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[Ne] 3s1",
    "commonUses": "Table salt, street lighting, soap",
    "explanation": "Soft metal; reacts vigorously with water.",
    "gridRow": 3,
    "gridCol": 1
  },
  {
    "symbol": "Mg",
    "name": "Magnesium",
    "atomicNumber": 12,
    "atomicMass": 24.305,
    "period": 3,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[Ne] 3s2",
    "commonUses": "Light alloys, fireworks, antacids",
    "explanation": "Burns with brilliant white flame.",
    "gridRow": 3,
    "gridCol": 2
  },
  {
    "symbol": "Al",
    "name": "Aluminium",
    "atomicNumber": 13,
    "atomicMass": 26.982,
    "period": 3,
    "group": 13,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Ne] 3s2 3p1",
    "commonUses": "Packaging, aircraft, construction",
    "explanation": "Abundant metal with excellent strength-to-weight ratio.",
    "gridRow": 3,
    "gridCol": 13
  },
  {
    "symbol": "Si",
    "name": "Silicon",
    "atomicNumber": 14,
    "atomicMass": 28.086,
    "period": 3,
    "group": 14,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Ne] 3s2 3p2",
    "commonUses": "Semiconductors, solar cells, glass",
    "explanation": "Foundation of modern electronics industry.",
    "gridRow": 3,
    "gridCol": 14
  },
  {
    "symbol": "P",
    "name": "Phosphorus",
    "atomicNumber": 15,
    "atomicMass": 30.974,
    "period": 3,
    "group": 15,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Ne] 3s2 3p3",
    "commonUses": "Fertilizers, detergents, DNA backbone",
    "explanation": "Exists in white, red, and black allotropes.",
    "gridRow": 3,
    "gridCol": 15
  },
  {
    "symbol": "S",
    "name": "Sulfur",
    "atomicNumber": 16,
    "atomicMass": 32.07,
    "period": 3,
    "group": 16,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Ne] 3s2 3p4",
    "commonUses": "Sulfuric acid, vulcanized rubber, fungicides",
    "explanation": "Yellow solid; essential in proteins and enzymes.",
    "gridRow": 3,
    "gridCol": 16
  },
  {
    "symbol": "Cl",
    "name": "Chlorine",
    "atomicNumber": 17,
    "atomicMass": 35.45,
    "period": 3,
    "group": 17,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Ne] 3s2 3p5",
    "commonUses": "Water disinfection, PVC, bleach",
    "explanation": "Greenish toxic gas; strong oxidizing agent.",
    "gridRow": 3,
    "gridCol": 17
  },
  {
    "symbol": "Ar",
    "name": "Argon",
    "atomicNumber": 18,
    "atomicMass": 39.948,
    "period": 3,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[Ne] 3s2 3p6",
    "commonUses": "Welding shield gas, incandescent bulbs",
    "explanation": "Most abundant noble gas in atmosphere.",
    "gridRow": 3,
    "gridCol": 18
  },
  {
    "symbol": "K",
    "name": "Potassium",
    "atomicNumber": 19,
    "atomicMass": 39.098,
    "period": 4,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[Ar] 4s1",
    "commonUses": "Fertilizers, glass, food preservatives",
    "explanation": "Essential nutrient for nerve and muscle function.",
    "gridRow": 4,
    "gridCol": 1
  },
  {
    "symbol": "Ca",
    "name": "Calcium",
    "atomicNumber": 20,
    "atomicMass": 40.078,
    "period": 4,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[Ar] 4s2",
    "commonUses": "Cement, bones, dietary supplements",
    "explanation": "Major component of bones and teeth.",
    "gridRow": 4,
    "gridCol": 2
  },
  {
    "symbol": "Sc",
    "name": "Scandium",
    "atomicNumber": 21,
    "atomicMass": 44.956,
    "period": 4,
    "group": 3,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d1 4s2",
    "commonUses": "Aerospace alloys, stadium lighting",
    "explanation": "Light transition metal; rare in Earth crust.",
    "gridRow": 4,
    "gridCol": 3
  },
  {
    "symbol": "Ti",
    "name": "Titanium",
    "atomicNumber": 22,
    "atomicMass": 47.867,
    "period": 4,
    "group": 4,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d2 4s2",
    "commonUses": "Aircraft, implants, pigments",
    "explanation": "Strong, corrosion-resistant, biocompatible.",
    "gridRow": 4,
    "gridCol": 4
  },
  {
    "symbol": "V",
    "name": "Vanadium",
    "atomicNumber": 23,
    "atomicMass": 50.942,
    "period": 4,
    "group": 5,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d3 4s2",
    "commonUses": "Steel alloys, catalysts, batteries",
    "explanation": "Hardens steel; used in tool alloys.",
    "gridRow": 4,
    "gridCol": 5
  },
  {
    "symbol": "Cr",
    "name": "Chromium",
    "atomicNumber": 24,
    "atomicMass": 51.996,
    "period": 4,
    "group": 6,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d5 4s1",
    "commonUses": "Stainless steel, chrome plating, pigments",
    "explanation": "Gives stainless steel its corrosion resistance.",
    "gridRow": 4,
    "gridCol": 6
  },
  {
    "symbol": "Mn",
    "name": "Manganese",
    "atomicNumber": 25,
    "atomicMass": 54.938,
    "period": 4,
    "group": 7,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d5 4s2",
    "commonUses": "Steel production, batteries, fertilizers",
    "explanation": "Essential trace element for enzymes.",
    "gridRow": 4,
    "gridCol": 7
  },
  {
    "symbol": "Fe",
    "name": "Iron",
    "atomicNumber": 26,
    "atomicMass": 55.845,
    "period": 4,
    "group": 8,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d6 4s2",
    "commonUses": "Steel, hemoglobin, magnets, construction",
    "explanation": "Most used metal; core of Earth.",
    "gridRow": 4,
    "gridCol": 8
  },
  {
    "symbol": "Co",
    "name": "Cobalt",
    "atomicNumber": 27,
    "atomicMass": 58.933,
    "period": 4,
    "group": 9,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d7 4s2",
    "commonUses": "Batteries, pigments, medical isotopes",
    "explanation": "Magnetic; essential vitamin B12 component.",
    "gridRow": 4,
    "gridCol": 9
  },
  {
    "symbol": "Ni",
    "name": "Nickel",
    "atomicNumber": 28,
    "atomicMass": 58.693,
    "period": 4,
    "group": 10,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d8 4s2",
    "commonUses": "Stainless steel, coins, rechargeable batteries",
    "explanation": "Corrosion-resistant; ferromagnetic.",
    "gridRow": 4,
    "gridCol": 10
  },
  {
    "symbol": "Cu",
    "name": "Copper",
    "atomicNumber": 29,
    "atomicMass": 63.546,
    "period": 4,
    "group": 11,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d10 4s1",
    "commonUses": "Electrical wiring, plumbing, alloys",
    "explanation": "Excellent electrical and thermal conductor.",
    "gridRow": 4,
    "gridCol": 11
  },
  {
    "symbol": "Zn",
    "name": "Zinc",
    "atomicNumber": 30,
    "atomicMass": 65.38,
    "period": 4,
    "group": 12,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Ar] 3d10 4s2",
    "commonUses": "Galvanizing, brass, dietary supplements",
    "explanation": "Protects steel from rust via galvanization.",
    "gridRow": 4,
    "gridCol": 12
  },
  {
    "symbol": "Ga",
    "name": "Gallium",
    "atomicNumber": 31,
    "atomicMass": 69.723,
    "period": 4,
    "group": 13,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Ar] 3d10 4s2 4p1",
    "commonUses": "Semiconductors, LEDs, thermometers",
    "explanation": "Melts in your hand; used in GaAs chips.",
    "gridRow": 4,
    "gridCol": 13
  },
  {
    "symbol": "Ge",
    "name": "Germanium",
    "atomicNumber": 32,
    "atomicMass": 72.63,
    "period": 4,
    "group": 14,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Ar] 3d10 4s2 4p2",
    "commonUses": "Fiber optics, infrared optics, transistors",
    "explanation": "Semiconductor; improves silicon transistor speed.",
    "gridRow": 4,
    "gridCol": 14
  },
  {
    "symbol": "As",
    "name": "Arsenic",
    "atomicNumber": 33,
    "atomicMass": 74.922,
    "period": 4,
    "group": 15,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Ar] 3d10 4s2 4p3",
    "commonUses": "Semiconductors, wood preservatives, pesticides",
    "explanation": "Toxic metalloid; semiconductor dopant.",
    "gridRow": 4,
    "gridCol": 15
  },
  {
    "symbol": "Se",
    "name": "Selenium",
    "atomicNumber": 34,
    "atomicMass": 78.971,
    "period": 4,
    "group": 16,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Ar] 3d10 4s2 4p4",
    "commonUses": "Photocopiers, glass, dietary supplements",
    "explanation": "Photoconductor; antioxidant in biology.",
    "gridRow": 4,
    "gridCol": 16
  },
  {
    "symbol": "Br",
    "name": "Bromine",
    "atomicNumber": 35,
    "atomicMass": 79.904,
    "period": 4,
    "group": 17,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Ar] 3d10 4s2 4p5",
    "commonUses": "Flame retardants, photography, medicines",
    "explanation": "Only liquid nonmetal at room temperature.",
    "gridRow": 4,
    "gridCol": 17
  },
  {
    "symbol": "Kr",
    "name": "Krypton",
    "atomicNumber": 36,
    "atomicMass": 83.798,
    "period": 4,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[Ar] 3d10 4s2 4p6",
    "commonUses": "Lighting, lasers, insulation windows",
    "explanation": "Noble gas used in high-efficiency lighting.",
    "gridRow": 4,
    "gridCol": 18
  },
  {
    "symbol": "Rb",
    "name": "Rubidium",
    "atomicNumber": 37,
    "atomicMass": 85.468,
    "period": 5,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[Kr] 5s1",
    "commonUses": "Research, atomic clocks, fireworks",
    "explanation": "Highly reactive alkali metal.",
    "gridRow": 5,
    "gridCol": 1
  },
  {
    "symbol": "Sr",
    "name": "Strontium",
    "atomicNumber": 38,
    "atomicMass": 87.62,
    "period": 5,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[Kr] 5s2",
    "commonUses": "Fireworks red color, magnets, glass",
    "explanation": "Produces crimson-red flame color.",
    "gridRow": 5,
    "gridCol": 2
  },
  {
    "symbol": "Y",
    "name": "Yttrium",
    "atomicNumber": 39,
    "atomicMass": 88.906,
    "period": 5,
    "group": 3,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d1 5s2",
    "commonUses": "LED phosphors, superconductors, alloys",
    "explanation": "Used in YBCO high-temperature superconductors.",
    "gridRow": 5,
    "gridCol": 3
  },
  {
    "symbol": "Zr",
    "name": "Zirconium",
    "atomicNumber": 40,
    "atomicMass": 91.224,
    "period": 5,
    "group": 4,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d2 5s2",
    "commonUses": "Nuclear reactors, ceramics, jewelry",
    "explanation": "Low neutron absorption; corrosion resistant.",
    "gridRow": 5,
    "gridCol": 4
  },
  {
    "symbol": "Nb",
    "name": "Niobium",
    "atomicNumber": 41,
    "atomicMass": 92.906,
    "period": 5,
    "group": 5,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d4 5s1",
    "commonUses": "Superconducting magnets, steel, jet engines",
    "explanation": "Superconducts at low temperatures.",
    "gridRow": 5,
    "gridCol": 5
  },
  {
    "symbol": "Mo",
    "name": "Molybdenum",
    "atomicNumber": 42,
    "atomicMass": 95.95,
    "period": 5,
    "group": 6,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d5 5s1",
    "commonUses": "Alloy steels, catalysts, lubricants",
    "explanation": "Essential enzyme cofactor in nitrogen fixation.",
    "gridRow": 5,
    "gridCol": 6
  },
  {
    "symbol": "Tc",
    "name": "Technetium",
    "atomicNumber": 43,
    "atomicMass": 98,
    "period": 5,
    "group": 7,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d5 5s2",
    "commonUses": "Medical imaging, corrosion tracer",
    "explanation": "First artificially produced element.",
    "gridRow": 5,
    "gridCol": 7
  },
  {
    "symbol": "Ru",
    "name": "Ruthenium",
    "atomicNumber": 44,
    "atomicMass": 101.07,
    "period": 5,
    "group": 8,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d7 5s1",
    "commonUses": "Catalysts, electronics, jewelry plating",
    "explanation": "Rare platinum-group metal.",
    "gridRow": 5,
    "gridCol": 8
  },
  {
    "symbol": "Rh",
    "name": "Rhodium",
    "atomicNumber": 45,
    "atomicMass": 102.91,
    "period": 5,
    "group": 9,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d8 5s1",
    "commonUses": "Catalytic converters, jewelry, mirrors",
    "explanation": "Extremely rare; excellent catalyst.",
    "gridRow": 5,
    "gridCol": 9
  },
  {
    "symbol": "Pd",
    "name": "Palladium",
    "atomicNumber": 46,
    "atomicMass": 106.42,
    "period": 5,
    "group": 10,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d10",
    "commonUses": "Catalytic converters, electronics, dentistry",
    "explanation": "Absorbs hydrogen; precious catalyst metal.",
    "gridRow": 5,
    "gridCol": 10
  },
  {
    "symbol": "Ag",
    "name": "Silver",
    "atomicNumber": 47,
    "atomicMass": 107.87,
    "period": 5,
    "group": 11,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d10 5s1",
    "commonUses": "Jewelry, photography, electronics, coins",
    "explanation": "Best electrical conductor of all metals.",
    "gridRow": 5,
    "gridCol": 11
  },
  {
    "symbol": "Cd",
    "name": "Cadmium",
    "atomicNumber": 48,
    "atomicMass": 112.41,
    "period": 5,
    "group": 12,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Kr] 4d10 5s2",
    "commonUses": "Batteries, pigments, nuclear reactors",
    "explanation": "Toxic heavy metal; used in NiCd batteries.",
    "gridRow": 5,
    "gridCol": 12
  },
  {
    "symbol": "In",
    "name": "Indium",
    "atomicNumber": 49,
    "atomicMass": 114.82,
    "period": 5,
    "group": 13,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Kr] 4d10 5s2 5p1",
    "commonUses": "Touch screens, solders, semiconductors",
    "explanation": "Soft metal; forms transparent conductive oxide.",
    "gridRow": 5,
    "gridCol": 13
  },
  {
    "symbol": "Sn",
    "name": "Tin",
    "atomicNumber": 50,
    "atomicMass": 118.71,
    "period": 5,
    "group": 14,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Kr] 4d10 5s2 5p2",
    "commonUses": "Solder, tinplate, bronze alloys",
    "explanation": "Low melting point; prevents iron corrosion.",
    "gridRow": 5,
    "gridCol": 14
  },
  {
    "symbol": "Sb",
    "name": "Antimony",
    "atomicNumber": 51,
    "atomicMass": 121.76,
    "period": 5,
    "group": 15,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Kr] 4d10 5s2 5p3",
    "commonUses": "Flame retardants, batteries, semiconductors",
    "explanation": "Brittle metalloid; expands on solidifying.",
    "gridRow": 5,
    "gridCol": 15
  },
  {
    "symbol": "Te",
    "name": "Tellurium",
    "atomicNumber": 52,
    "atomicMass": 127.6,
    "period": 5,
    "group": 16,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Kr] 4d10 5s2 5p4",
    "commonUses": "Solar cells, alloys, thermoelectrics",
    "explanation": "Rare metalloid; improves steel machinability.",
    "gridRow": 5,
    "gridCol": 16
  },
  {
    "symbol": "I",
    "name": "Iodine",
    "atomicNumber": 53,
    "atomicMass": 126.9,
    "period": 5,
    "group": 17,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Kr] 4d10 5s2 5p5",
    "commonUses": "Disinfectants, thyroid medicine, dyes",
    "explanation": "Essential nutrient for thyroid hormones.",
    "gridRow": 5,
    "gridCol": 17
  },
  {
    "symbol": "Xe",
    "name": "Xenon",
    "atomicNumber": 54,
    "atomicMass": 131.29,
    "period": 5,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[Kr] 4d10 5s2 5p6",
    "commonUses": "Lighting, anesthesia, ion propulsion",
    "explanation": "Noble gas used in ion thrusters.",
    "gridRow": 5,
    "gridCol": 18
  },
  {
    "symbol": "Cs",
    "name": "Caesium",
    "atomicNumber": 55,
    "atomicMass": 132.91,
    "period": 6,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[Xe] 6s1",
    "commonUses": "Atomic clocks, drilling fluids, photoelectric cells",
    "explanation": "Most electropositive stable element.",
    "gridRow": 6,
    "gridCol": 1
  },
  {
    "symbol": "Ba",
    "name": "Barium",
    "atomicNumber": 56,
    "atomicMass": 137.33,
    "period": 6,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[Xe] 6s2",
    "commonUses": "Medical imaging, fireworks, glass",
    "explanation": "Heavy alkaline earth; green flame color.",
    "gridRow": 6,
    "gridCol": 2
  },
  {
    "symbol": "La",
    "name": "Lanthanum",
    "atomicNumber": 57,
    "atomicMass": 138.91,
    "period": 6,
    "group": 3,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 5d1 6s2",
    "commonUses": "Camera lenses, catalysts, batteries",
    "explanation": "First lanthanide; soft silvery metal.",
    "gridRow": 6,
    "gridCol": 3
  },
  {
    "symbol": "Ce",
    "name": "Cerium",
    "atomicNumber": 58,
    "atomicMass": 140.12,
    "period": 8,
    "group": 4,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f1 5d1 6s2",
    "commonUses": "Catalytic converters, polishing, alloys",
    "explanation": "Most abundant rare earth element.",
    "gridRow": 8,
    "gridCol": 4
  },
  {
    "symbol": "Pr",
    "name": "Praseodymium",
    "atomicNumber": 59,
    "atomicMass": 140.91,
    "period": 8,
    "group": 5,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f3 6s2",
    "commonUses": "Magnets, glass coloring, aircraft engines",
    "explanation": "Creates intense yellow-green glass color.",
    "gridRow": 8,
    "gridCol": 5
  },
  {
    "symbol": "Nd",
    "name": "Neodymium",
    "atomicNumber": 60,
    "atomicMass": 144.24,
    "period": 8,
    "group": 6,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f4 6s2",
    "commonUses": "Powerful magnets, lasers, glass",
    "explanation": "Makes strongest permanent magnets.",
    "gridRow": 8,
    "gridCol": 6
  },
  {
    "symbol": "Pm",
    "name": "Promethium",
    "atomicNumber": 61,
    "atomicMass": 145,
    "period": 8,
    "group": 7,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f5 6s2",
    "commonUses": "Nuclear batteries, luminous paint",
    "explanation": "All isotopes radioactive; no stable form.",
    "gridRow": 8,
    "gridCol": 7
  },
  {
    "symbol": "Sm",
    "name": "Samarium",
    "atomicNumber": 62,
    "atomicMass": 150.36,
    "period": 8,
    "group": 8,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f6 6s2",
    "commonUses": "Magnets, cancer treatment, nuclear reactors",
    "explanation": "Used in SmCo permanent magnets.",
    "gridRow": 8,
    "gridCol": 8
  },
  {
    "symbol": "Eu",
    "name": "Europium",
    "atomicNumber": 63,
    "atomicMass": 151.96,
    "period": 8,
    "group": 9,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f7 6s2",
    "commonUses": "Phosphors, Euro banknotes, LEDs",
    "explanation": "Produces red and blue phosphor colors.",
    "gridRow": 8,
    "gridCol": 9
  },
  {
    "symbol": "Gd",
    "name": "Gadolinium",
    "atomicNumber": 64,
    "atomicMass": 157.25,
    "period": 8,
    "group": 10,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f7 5d1 6s2",
    "commonUses": "MRI contrast, neutron capture, magnets",
    "explanation": "MRI contrast agent; high neutron absorption.",
    "gridRow": 8,
    "gridCol": 10
  },
  {
    "symbol": "Tb",
    "name": "Terbium",
    "atomicNumber": 65,
    "atomicMass": 158.93,
    "period": 8,
    "group": 11,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f9 6s2",
    "commonUses": "Green phosphors, magnets, sonar",
    "explanation": "Produces green phosphorescence.",
    "gridRow": 8,
    "gridCol": 11
  },
  {
    "symbol": "Dy",
    "name": "Dysprosium",
    "atomicNumber": 66,
    "atomicMass": 162.5,
    "period": 8,
    "group": 12,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f10 6s2",
    "commonUses": "Magnets, lasers, nuclear control rods",
    "explanation": "Improves magnet performance at high temperature.",
    "gridRow": 8,
    "gridCol": 12
  },
  {
    "symbol": "Ho",
    "name": "Holmium",
    "atomicNumber": 67,
    "atomicMass": 164.93,
    "period": 8,
    "group": 13,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f11 6s2",
    "commonUses": "Lasers, magnets, nuclear control",
    "explanation": "Highest magnetic moment of any element.",
    "gridRow": 8,
    "gridCol": 13
  },
  {
    "symbol": "Er",
    "name": "Erbium",
    "atomicNumber": 68,
    "atomicMass": 167.26,
    "period": 8,
    "group": 14,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f12 6s2",
    "commonUses": "Fiber optic amplifiers, lasers, metallurgy",
    "explanation": "Amplifies optical signals in fiber networks.",
    "gridRow": 8,
    "gridCol": 14
  },
  {
    "symbol": "Tm",
    "name": "Thulium",
    "atomicNumber": 69,
    "atomicMass": 168.93,
    "period": 8,
    "group": 15,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f13 6s2",
    "commonUses": "Portable X-ray, lasers, metallurgy",
    "explanation": "Least abundant stable lanthanide.",
    "gridRow": 8,
    "gridCol": 15
  },
  {
    "symbol": "Yb",
    "name": "Ytterbium",
    "atomicNumber": 70,
    "atomicMass": 173.05,
    "period": 8,
    "group": 16,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f14 6s2",
    "commonUses": "Lasers, stress gauges, atomic clocks",
    "explanation": "Used in high-precision atomic clocks.",
    "gridRow": 8,
    "gridCol": 16
  },
  {
    "symbol": "Lu",
    "name": "Lutetium",
    "atomicNumber": 71,
    "atomicMass": 174.97,
    "period": 8,
    "group": 17,
    "category": "lanthanide",
    "categoryLabel": "Lanthanides",
    "electronConfiguration": "[Xe] 4f14 5d1 6s2",
    "commonUses": "PET scan detectors, catalysts, research",
    "explanation": "Last and densest lanthanide.",
    "gridRow": 8,
    "gridCol": 17
  },
  {
    "symbol": "Hf",
    "name": "Hafnium",
    "atomicNumber": 72,
    "atomicMass": 178.49,
    "period": 6,
    "group": 4,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d2 6s2",
    "commonUses": "Nuclear control rods, microprocessors",
    "explanation": "Excellent neutron absorber in reactors.",
    "gridRow": 6,
    "gridCol": 4
  },
  {
    "symbol": "Ta",
    "name": "Tantalum",
    "atomicNumber": 73,
    "atomicMass": 180.95,
    "period": 6,
    "group": 5,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d3 6s2",
    "commonUses": "Capacitors, surgical implants, alloys",
    "explanation": "Biocompatible; resists all body fluids.",
    "gridRow": 6,
    "gridCol": 5
  },
  {
    "symbol": "W",
    "name": "Tungsten",
    "atomicNumber": 74,
    "atomicMass": 183.84,
    "period": 6,
    "group": 6,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d4 6s2",
    "commonUses": "Light bulb filaments, cutting tools, armor",
    "explanation": "Highest melting point of all metals.",
    "gridRow": 6,
    "gridCol": 6
  },
  {
    "symbol": "Re",
    "name": "Rhenium",
    "atomicNumber": 75,
    "atomicMass": 186.21,
    "period": 6,
    "group": 7,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d5 6s2",
    "commonUses": "Jet engines, catalysts, thermocouples",
    "explanation": "One of densest metals; extreme heat resistance.",
    "gridRow": 6,
    "gridCol": 7
  },
  {
    "symbol": "Os",
    "name": "Osmium",
    "atomicNumber": 76,
    "atomicMass": 190.23,
    "period": 6,
    "group": 8,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d6 6s2",
    "commonUses": "Pen tips, electrical contacts, alloys",
    "explanation": "Densest naturally occurring element.",
    "gridRow": 6,
    "gridCol": 8
  },
  {
    "symbol": "Ir",
    "name": "Iridium",
    "atomicNumber": 77,
    "atomicMass": 192.22,
    "period": 6,
    "group": 9,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d7 6s2",
    "commonUses": "Spark plugs, crucibles, standards",
    "explanation": "Most corrosion-resistant metal known.",
    "gridRow": 6,
    "gridCol": 9
  },
  {
    "symbol": "Pt",
    "name": "Platinum",
    "atomicNumber": 78,
    "atomicMass": 195.08,
    "period": 6,
    "group": 10,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d9 6s1",
    "commonUses": "Catalytic converters, jewelry, chemotherapy",
    "explanation": "Noble metal; excellent catalyst.",
    "gridRow": 6,
    "gridCol": 10
  },
  {
    "symbol": "Au",
    "name": "Gold",
    "atomicNumber": 79,
    "atomicMass": 196.97,
    "period": 6,
    "group": 11,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s1",
    "commonUses": "Jewelry, electronics, currency, dentistry",
    "explanation": "Noble metal; does not tarnish.",
    "gridRow": 6,
    "gridCol": 11
  },
  {
    "symbol": "Hg",
    "name": "Mercury",
    "atomicNumber": 80,
    "atomicMass": 200.59,
    "period": 6,
    "group": 12,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2",
    "commonUses": "Thermometers, barometers, amalgams",
    "explanation": "Only metal liquid at room temperature.",
    "gridRow": 6,
    "gridCol": 12
  },
  {
    "symbol": "Tl",
    "name": "Thallium",
    "atomicNumber": 81,
    "atomicMass": 204.38,
    "period": 6,
    "group": 13,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p1",
    "commonUses": "Electronics, glass, rat poison",
    "explanation": "Highly toxic post-transition metal.",
    "gridRow": 6,
    "gridCol": 13
  },
  {
    "symbol": "Pb",
    "name": "Lead",
    "atomicNumber": 82,
    "atomicMass": 207.2,
    "period": 6,
    "group": 14,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p2",
    "commonUses": "Batteries, radiation shielding, pipes",
    "explanation": "Dense, soft; neurotoxic heavy metal.",
    "gridRow": 6,
    "gridCol": 14
  },
  {
    "symbol": "Bi",
    "name": "Bismuth",
    "atomicNumber": 83,
    "atomicMass": 208.98,
    "period": 6,
    "group": 15,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p3",
    "commonUses": "Pharmaceuticals, cosmetics, alloys",
    "explanation": "Low-toxicity heavy metal; rainbow crystals.",
    "gridRow": 6,
    "gridCol": 15
  },
  {
    "symbol": "Po",
    "name": "Polonium",
    "atomicNumber": 84,
    "atomicMass": 209,
    "period": 6,
    "group": 16,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p4",
    "commonUses": "Anti-static devices, nuclear triggers",
    "explanation": "Highly radioactive; discovered by Curie.",
    "gridRow": 6,
    "gridCol": 16
  },
  {
    "symbol": "At",
    "name": "Astatine",
    "atomicNumber": 85,
    "atomicMass": 210,
    "period": 6,
    "group": 17,
    "category": "metalloid",
    "categoryLabel": "Metalloids",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p5",
    "commonUses": "Cancer research, radiotherapy",
    "explanation": "Rarest naturally occurring element.",
    "gridRow": 6,
    "gridCol": 17
  },
  {
    "symbol": "Rn",
    "name": "Radon",
    "atomicNumber": 86,
    "atomicMass": 222,
    "period": 6,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[Xe] 4f14 5d10 6s2 6p6",
    "commonUses": "Cancer risk studies, earthquake prediction",
    "explanation": "Radioactive noble gas; indoor air hazard.",
    "gridRow": 6,
    "gridCol": 18
  },
  {
    "symbol": "Fr",
    "name": "Francium",
    "atomicNumber": 87,
    "atomicMass": 223,
    "period": 7,
    "group": 1,
    "category": "alkali-metal",
    "categoryLabel": "Alkali metals",
    "electronConfiguration": "[Rn] 7s1",
    "commonUses": "Scientific research only",
    "explanation": "Extremely radioactive; most unstable alkali.",
    "gridRow": 7,
    "gridCol": 1
  },
  {
    "symbol": "Ra",
    "name": "Radium",
    "atomicNumber": 88,
    "atomicMass": 226,
    "period": 7,
    "group": 2,
    "category": "alkaline-earth",
    "categoryLabel": "Alkaline earth metals",
    "electronConfiguration": "[Rn] 7s2",
    "commonUses": "Cancer treatment, luminous paint",
    "explanation": "Radioactive; glows in dark paint historically.",
    "gridRow": 7,
    "gridCol": 2
  },
  {
    "symbol": "Ac",
    "name": "Actinium",
    "atomicNumber": 89,
    "atomicMass": 227,
    "period": 7,
    "group": 3,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 6d1 7s2",
    "commonUses": "Neutron sources, cancer research",
    "explanation": "First actinide; highly radioactive.",
    "gridRow": 7,
    "gridCol": 3
  },
  {
    "symbol": "Th",
    "name": "Thorium",
    "atomicNumber": 90,
    "atomicMass": 232.04,
    "period": 9,
    "group": 4,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 6d2 7s2",
    "commonUses": "Nuclear fuel, gas mantles, alloys",
    "explanation": "Potential nuclear fuel; more abundant than uranium.",
    "gridRow": 9,
    "gridCol": 4
  },
  {
    "symbol": "Pa",
    "name": "Protactinium",
    "atomicNumber": 91,
    "atomicMass": 231.04,
    "period": 9,
    "group": 5,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f2 6d1 7s2",
    "commonUses": "Scientific research",
    "explanation": "Rare radioactive actinide.",
    "gridRow": 9,
    "gridCol": 5
  },
  {
    "symbol": "U",
    "name": "Uranium",
    "atomicNumber": 92,
    "atomicMass": 238.03,
    "period": 9,
    "group": 6,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f3 6d1 7s2",
    "commonUses": "Nuclear power, weapons, dating rocks",
    "explanation": "Fissile; powers nuclear reactors.",
    "gridRow": 9,
    "gridCol": 6
  },
  {
    "symbol": "Np",
    "name": "Neptunium",
    "atomicNumber": 93,
    "atomicMass": 237,
    "period": 9,
    "group": 7,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f4 6d1 7s2",
    "commonUses": "Neutron detection, research",
    "explanation": "First transuranium element synthesized.",
    "gridRow": 9,
    "gridCol": 7
  },
  {
    "symbol": "Pu",
    "name": "Plutonium",
    "atomicNumber": 94,
    "atomicMass": 244,
    "period": 9,
    "group": 8,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f6 7s2",
    "commonUses": "Nuclear weapons, RTGs, research",
    "explanation": "Key fissile material; extremely toxic.",
    "gridRow": 9,
    "gridCol": 8
  },
  {
    "symbol": "Am",
    "name": "Americium",
    "atomicNumber": 95,
    "atomicMass": 243,
    "period": 9,
    "group": 9,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f7 7s2",
    "commonUses": "Smoke detectors, research",
    "explanation": "Ionizes air in household smoke alarms.",
    "gridRow": 9,
    "gridCol": 9
  },
  {
    "symbol": "Cm",
    "name": "Curium",
    "atomicNumber": 96,
    "atomicMass": 247,
    "period": 9,
    "group": 10,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f7 6d1 7s2",
    "commonUses": "Space power, research",
    "explanation": "Named after Marie and Pierre Curie.",
    "gridRow": 9,
    "gridCol": 10
  },
  {
    "symbol": "Bk",
    "name": "Berkelium",
    "atomicNumber": 97,
    "atomicMass": 247,
    "period": 9,
    "group": 11,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f9 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Berkeley, California.",
    "gridRow": 9,
    "gridCol": 11
  },
  {
    "symbol": "Cf",
    "name": "Californium",
    "atomicNumber": 98,
    "atomicMass": 251,
    "period": 9,
    "group": 12,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f10 7s2",
    "commonUses": "Neutron sources, cancer treatment",
    "explanation": "Powerful neutron emitter.",
    "gridRow": 9,
    "gridCol": 12
  },
  {
    "symbol": "Es",
    "name": "Einsteinium",
    "atomicNumber": 99,
    "atomicMass": 252,
    "period": 9,
    "group": 13,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f11 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Albert Einstein.",
    "gridRow": 9,
    "gridCol": 13
  },
  {
    "symbol": "Fm",
    "name": "Fermium",
    "atomicNumber": 100,
    "atomicMass": 257,
    "period": 9,
    "group": 14,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f12 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Enrico Fermi.",
    "gridRow": 9,
    "gridCol": 14
  },
  {
    "symbol": "Md",
    "name": "Mendelevium",
    "atomicNumber": 101,
    "atomicMass": 258,
    "period": 9,
    "group": 15,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f13 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Dmitri Mendeleev.",
    "gridRow": 9,
    "gridCol": 15
  },
  {
    "symbol": "No",
    "name": "Nobelium",
    "atomicNumber": 102,
    "atomicMass": 259,
    "period": 9,
    "group": 16,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f14 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Alfred Nobel.",
    "gridRow": 9,
    "gridCol": 16
  },
  {
    "symbol": "Lr",
    "name": "Lawrencium",
    "atomicNumber": 103,
    "atomicMass": 266,
    "period": 9,
    "group": 17,
    "category": "actinide",
    "categoryLabel": "Actinides",
    "electronConfiguration": "[Rn] 5f14 7d1 7s2",
    "commonUses": "Scientific research",
    "explanation": "Last actinide; named after Ernest Lawrence.",
    "gridRow": 9,
    "gridCol": 17
  },
  {
    "symbol": "Rf",
    "name": "Rutherfordium",
    "atomicNumber": 104,
    "atomicMass": 267,
    "period": 7,
    "group": 4,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d2 7s2",
    "commonUses": "Scientific research",
    "explanation": "Superheavy synthetic element.",
    "gridRow": 7,
    "gridCol": 4
  },
  {
    "symbol": "Db",
    "name": "Dubnium",
    "atomicNumber": 105,
    "atomicMass": 268,
    "period": 7,
    "group": 5,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d3 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Dubna, Russia.",
    "gridRow": 7,
    "gridCol": 5
  },
  {
    "symbol": "Sg",
    "name": "Seaborgium",
    "atomicNumber": 106,
    "atomicMass": 269,
    "period": 7,
    "group": 6,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d4 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Glenn Seaborg.",
    "gridRow": 7,
    "gridCol": 6
  },
  {
    "symbol": "Bh",
    "name": "Bohrium",
    "atomicNumber": 107,
    "atomicMass": 270,
    "period": 7,
    "group": 7,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d5 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Niels Bohr.",
    "gridRow": 7,
    "gridCol": 7
  },
  {
    "symbol": "Hs",
    "name": "Hassium",
    "atomicNumber": 108,
    "atomicMass": 277,
    "period": 7,
    "group": 8,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d6 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after German state Hesse.",
    "gridRow": 7,
    "gridCol": 8
  },
  {
    "symbol": "Mt",
    "name": "Meitnerium",
    "atomicNumber": 109,
    "atomicMass": 278,
    "period": 7,
    "group": 9,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d7 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Lise Meitner.",
    "gridRow": 7,
    "gridCol": 9
  },
  {
    "symbol": "Ds",
    "name": "Darmstadtium",
    "atomicNumber": 110,
    "atomicMass": 281,
    "period": 7,
    "group": 10,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d8 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Darmstadt, Germany.",
    "gridRow": 7,
    "gridCol": 10
  },
  {
    "symbol": "Rg",
    "name": "Roentgenium",
    "atomicNumber": 111,
    "atomicMass": 282,
    "period": 7,
    "group": 11,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d9 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Wilhelm Röntgen.",
    "gridRow": 7,
    "gridCol": 11
  },
  {
    "symbol": "Cn",
    "name": "Copernicium",
    "atomicNumber": 112,
    "atomicMass": 285,
    "period": 7,
    "group": 12,
    "category": "transition-metal",
    "categoryLabel": "Transition metals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2",
    "commonUses": "Scientific research",
    "explanation": "Named after Nicolaus Copernicus.",
    "gridRow": 7,
    "gridCol": 12
  },
  {
    "symbol": "Nh",
    "name": "Nihonium",
    "atomicNumber": 113,
    "atomicMass": 286,
    "period": 7,
    "group": 13,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p1",
    "commonUses": "Scientific research",
    "explanation": "First element discovered in Asia.",
    "gridRow": 7,
    "gridCol": 13
  },
  {
    "symbol": "Fl",
    "name": "Flerovium",
    "atomicNumber": 114,
    "atomicMass": 289,
    "period": 7,
    "group": 14,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p2",
    "commonUses": "Scientific research",
    "explanation": "Named after Flerov Laboratory.",
    "gridRow": 7,
    "gridCol": 14
  },
  {
    "symbol": "Mc",
    "name": "Moscovium",
    "atomicNumber": 115,
    "atomicMass": 290,
    "period": 7,
    "group": 15,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p3",
    "commonUses": "Scientific research",
    "explanation": "Named after Moscow Oblast.",
    "gridRow": 7,
    "gridCol": 15
  },
  {
    "symbol": "Lv",
    "name": "Livermorium",
    "atomicNumber": 116,
    "atomicMass": 293,
    "period": 7,
    "group": 16,
    "category": "post-transition-metal",
    "categoryLabel": "Post-transition metals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p4",
    "commonUses": "Scientific research",
    "explanation": "Named after Livermore, California.",
    "gridRow": 7,
    "gridCol": 16
  },
  {
    "symbol": "Ts",
    "name": "Tennessine",
    "atomicNumber": 117,
    "atomicMass": 294,
    "period": 7,
    "group": 17,
    "category": "reactive-nonmetal",
    "categoryLabel": "Nonmetals",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p5",
    "commonUses": "Scientific research",
    "explanation": "Named after Tennessee, USA.",
    "gridRow": 7,
    "gridCol": 17
  },
  {
    "symbol": "Og",
    "name": "Oganesson",
    "atomicNumber": 118,
    "atomicMass": 294,
    "period": 7,
    "group": 18,
    "category": "noble-gas",
    "categoryLabel": "Noble gases",
    "electronConfiguration": "[Rn] 5f14 6d10 7s2 7p6",
    "commonUses": "Scientific research",
    "explanation": "Heaviest known element; noble gas-like.",
    "gridRow": 7,
    "gridCol": 18
  }
];

export function getCategoryColor(category: ElementCategory): string {
  return (
    elementCategories.find((item) => item.id === category)?.color ?? "#94a3b8"
  );
}
